### ISSUE TITLE
Partnerhochschule hinzufügen bearbeiten

### ISSUE THREAD

**Issue by mpeeps02** [mpeeps02/I2_Webuserinterface_Datenbankverwaltung#43]
Wenn man auf den Button Partnerhochschule hinzufügen klickt, bekommt man ein Popup-Fenster. 
Dort bitte unter Ansprechpersonen Titel, Geschlecht, Funktion und Telefonnummer entfernen.

**Comment by diewithdil** [comment]
Soll das Fenster eventuell vergrößert werden? 
Soll die Anordnung so beibehalten werden? 
Ist es i.O. wenn wir bei den Popup-Fenstern die Scrollmöglichkeit rausnehmen, wird eigentlich nicht benötigt?

**Comment by mpeeps02** [comment]
Scrollmöglichkeit kann eigentlich raus und Anordnung des Fensters mittig auf der Website würde ich vorschlagen
