### ISSUE TITLE
Verträge: Hochschulvereinbarung falsche Anzahl bzw doppelte Auflistung

### ISSUE THREAD

**Issue by mpeeps02** [mpeeps02/I2_Webuserinterface_Datenbankverwaltung#58]
Hier bitte heraus finden, woran diese doppelte Auflistung liegt.
Danach im neuen Issue Problem beheben.

**Comment by Pandigov** [comment]
Problem sind die klickbaren Zeilen der Hochschultabelle. Das Klick-Event wird doppelt/dreifach... ausgeführt sobald man versucht zu filtern oder die Filter zurückzusetzen. Es konnte kein logischer Grund für das aufgetretene Problem gefunden werden, daher wurde zur ursprünglichen Implementierung mit einem Bearbeiten-Knopf zurückgekehrt.
