### ISSUE TITLE
Speicherbutton in Verträge funktioniert nicht (blauer) + Vertrag speichern

### ISSUE THREAD

**Issue by mpeeps02** [mpeeps02/I2_Webuserinterface_Datenbankverwaltung#59]
Problem finden warum der untere Speicher Button nicht funktioniert.

**Comment by Pandigov** [comment]
Der untere Speicherbutton funktioniert, jedoch muss bei "neuer Vertrag" anlegen zuerst der schwarz umrandete Button getätigt werden um zwischenzuspeichern. Wenn man den blauen drückt werden die neuangelegten Daten dann endgültig in die Datenbank geschrieben
