### ISSUE TITLE
Rechtes Fenster: Mentorenwahl bearbeiten

### ISSUE THREAD

**Issue by mpeeps02** [mpeeps02/I2_Webuserinterface_Datenbankverwaltung#61]
Es gibt ein Dropdown Menü bei Mentoren und eine Option ist dort "Alle". Bitte diese Möglichkeit entfernen.

**Comment by diewithdil** [comment]
Kann erst gefixed werden, wenn die Mentorendaten gelöscht werden können. Die Auswahl "alle" kommt von einer Testanlegung eines Mentors. 


**In der Datenbank stehen die Testdaten nicht drinne**

**Comment by diewithdil** [comment]
Speicherung funktioniert, Testdatensätze fallen bei Übernahme weg. Die Löschfunktion wurde nach Absprache revidiert, da die Mitarbeiter anhand der Agreements die jeweiligen Mentoren einordnen.
